# Generated by Django 5.2.12 on 2026-03-14 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('scheduling', '0002_schedulebaseline_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('preliminaries', 'Preliminaries & General'), ('substructure', 'Substructure / Foundation'), ('superstructure', 'Superstructure'), ('roofing', 'Roofing'), ('mep', 'Mechanical & Electrical'), ('finishes', 'Finishes'), ('fittings', 'Doors, Windows & Fittings'), ('external', 'External Works'), ('earthworks', 'Earthworks & Grading'), ('drainage', 'Drainage & Structures'), ('pavement', 'Pavement / Surfacing'), ('specialist', 'Specialist Systems'), ('equipment', 'Equipment & Plant'), ('labour', 'Labour'), ('professional', 'Professional Fees'), ('contingency', 'Contingency'), ('other', 'Other')], default='other', max_length=30)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='scheduling.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cost_budget_line',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_date', models.DateField()),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('preliminaries', 'Preliminaries & General'), ('substructure', 'Substructure / Foundation'), ('superstructure', 'Superstructure'), ('roofing', 'Roofing'), ('mep', 'Mechanical & Electrical'), ('finishes', 'Finishes'), ('fittings', 'Doors, Windows & Fittings'), ('external', 'External Works'), ('earthworks', 'Earthworks & Grading'), ('drainage', 'Drainage & Structures'), ('pavement', 'Pavement / Surfacing'), ('specialist', 'Specialist Systems'), ('equipment', 'Equipment & Plant'), ('labour', 'Labour'), ('professional', 'Professional Fees'), ('contingency', 'Contingency'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='recorded', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cost.budgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='scheduling.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cost_expense',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
