# Generated by Django 5.2.12 on 2026-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_quotation_purchaseorder_quotation_rfq_quotation_rfq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
