# Generated by Django 5.2.12 on 2026-03-14 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Auto-generated human-readable project code, e.g. BP-RES-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('project_type', models.CharField(choices=[('residential', 'Residential House Construction'), ('commercial', 'Commercial Building'), ('road', 'Road Construction'), ('bridge', 'Bridge Construction'), ('water_treatment', 'Water Treatment Plant'), ('dam', 'Dam Construction'), ('school', 'School Building'), ('hospital', 'Hospital Construction'), ('custom', 'Custom Project')], max_length=30)),
                ('contract_type', models.CharField(choices=[('lump_sum', 'Lump Sum Contract'), ('admeasure', 'Admeasure / Re-measurement Contract'), ('cost_plus', 'Cost Plus Contract'), ('design_build', 'Design & Build Contract'), ('management', 'Management Contract'), ('turnkey', 'Turnkey Contract'), ('bot', 'BOT (Build-Operate-Transfer)'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('client_phone', models.CharField(blank=True, default='', max_length=50)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_org', models.CharField(blank=True, default='', max_length=255)),
                ('consultant', models.CharField(blank=True, default='', help_text='Lead consultant / supervising firm', max_length=255)),
                ('contractor', models.CharField(blank=True, default='', help_text='Main contractor / company name', max_length=255)),
                ('setup_complete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSetupConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase_templates', models.JSONField(default=list, help_text='List of phase/task group skeletons for the scheduling engine.')),
                ('milestone_templates', models.JSONField(default=list, help_text='List of milestone skeletons.')),
                ('has_design_phase', models.BooleanField(default=False, help_text='True if contract type includes design phases (D&B, Turnkey, BOT).')),
                ('workspace_modules', models.JSONField(default=list, help_text='List of enabled workspace module keys.')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_config', to='projects.project')),
            ],
            options={
                'db_table': 'projects_setup_config',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Project Manager'), ('engineer', 'Engineer'), ('qs', 'Quantity Surveyor'), ('supervisor', 'Site Supervisor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('permissions', models.JSONField(default=list, help_text='List of project-level permission codenames.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_membership',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
