# Generated by Django 5.2.12 on 2026-03-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changes', '0001_initial'),
        ('rfis', '0001_initial'),
        ('scheduling', '0002_schedulebaseline_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='related_rfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_orders', to='rfis.rfi'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_orders', to='scheduling.projecttask'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_orders_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='changeorder',
            unique_together={('project', 'code')},
        ),
    ]
