# Generated by Django 5.2.12 on 2026-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('progress', 'Progress Meeting'), ('safety', 'Safety Meeting'), ('design', 'Design Review'), ('handover', 'Handover'), ('site', 'Site Meeting'), ('client', 'Client Meeting'), ('other', 'Other')], default='progress', max_length=20),
        ),
    ]
