# Generated by Django 5.2.12 on 2026-03-25 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('comms', '0002_alter_meeting_meeting_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chat_messages', to='accounts.organisation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comms_org_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
