# Generated by Django 5.2.12 on 2026-03-14 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('export', 'Report Export'), ('ai_narrative', 'AI Narrative'), ('ai_report_draft', 'AI Report Draft'), ('ai_copilot', 'AI Copilot Query'), ('ai_other', 'AI Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('output_reference', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_jobs', to='projects.project')),
            ],
            options={
                'db_table': 'ai_async_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('narrative', 'Cost/Schedule Narrative'), ('report_draft', 'Report Draft'), ('copilot', 'Project Copilot')], max_length=30)),
                ('provider', models.CharField(default='gemini', max_length=30)),
                ('model_id', models.CharField(default='', max_length=60)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('request_summary', models.TextField(blank=True, default='')),
                ('context_token_estimate', models.IntegerField(default=0)),
                ('response_summary', models.TextField(blank=True, default='')),
                ('response_length', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
                ('async_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='ai.asyncjob')),
            ],
            options={
                'db_table': 'ai_request_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
