# Generated by Django 5.2.12 on 2026-03-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='discipline',
            field=models.CharField(blank=True, choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('civil', 'Civil'), ('geotechnical', 'Geotechnical'), ('environmental', 'Environmental'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('approved', 'Approved'), ('issued', 'Issued'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='issue_purpose',
            field=models.CharField(blank=True, choices=[('for_information', 'For Information'), ('for_review', 'For Review'), ('for_approval', 'For Approval'), ('for_construction', 'For Construction'), ('as_built', 'As Built'), ('record', 'Record')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('drawings', 'Drawings & Plans'), ('contracts', 'Contract Documents'), ('permits', 'Permits & Approvals'), ('specifications', 'Specifications'), ('reports', 'Reports'), ('correspondence', 'Correspondence'), ('photos', 'Photos'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
