# Generated by Django 5.2.12 on 2026-03-14 20:55

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('cross_project', 'Cross-Project')], default='project', max_length=20)),
                ('report_key', models.CharField(choices=[('progress', 'Progress'), ('financial', 'Financial'), ('schedule', 'Schedule'), ('procurement', 'Procurement'), ('safety', 'Safety'), ('quality', 'Quality'), ('labour', 'Labour'), ('risk', 'Risk'), ('documents', 'Documents'), ('meetings', 'Meetings')], max_length=30)),
                ('format', models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to=apps.reports.models.report_export_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='accounts.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_export',
                'ordering': ['-created_at'],
            },
        ),
    ]
