# Generated by Django 5.2.12 on 2026-03-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportexport',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('docx', 'Word')], default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportexport',
            name='report_key',
            field=models.CharField(choices=[('progress', 'Project Progress'), ('financial', 'Financial Summary'), ('schedule', 'Schedule Summary'), ('procurement', 'Procurement Summary'), ('safety', 'Safety Report'), ('quality', 'Quality Report'), ('labour', 'Labour / Timesheets'), ('risk', 'Risk Register'), ('rfi', 'RFI Register'), ('changes', 'Change Orders'), ('punch', 'Punch List'), ('documents', 'Document Register'), ('meetings', 'Meetings & Actions')], max_length=30),
        ),
    ]
