import { useParams } from 'react-router-dom'
import { useEffect, useState, type ReactNode } from 'react'
import {
  PageHeader, CostCard, DataTable, StatusBadge, ActionButton,
  Modal, LoadingState, EmptyState, Tabs,
} from '../../components/ui'
import {
  usePurchaseOrders, useProcurementSummary, useCreatePO,
  useSuppliers, useRFQs, useCreateRFQ,
  useQuotations, useCreateQuotation,
  useGoodsReceipts, useCreateGRN,
  useProcurementInvoices, useCreateInvoice,
  useProcurementPayments, useCreatePayment,
  type SupplierData, type PurchaseOrderData, type RFQData,
  type QuotationData, type GoodsReceiptData,
  type ProcurementInvoiceData, type ProcurementPaymentData,
} from '../../hooks/useProcurement'
import { useProject } from '../../hooks/useProjects'
import { useQueryClient } from '@tanstack/react-query'
import { useProjectPermissions } from '../../hooks/useProjectPermissions'
import { useUIStore } from '../../stores/uiStore'
import { formatDate, formatUGX } from '../../lib/formatters'
import { downloadText } from '../../lib/download'
import { api } from '../../api/client'

/**
 * Procurement page -- 8 tabbed views: Summary, Suppliers, RFQs, Quotations,
 * POs, GRNs, Invoices, Payments. Each tab has a DataTable + create modals.
 * No code fields in create modals (auto-generated by backend).
 */

const TABS = [
  { key: 'summary', label: 'Dashboard' },
  { key: 'suppliers', label: 'Suppliers' },
  { key: 'rfqs', label: 'RFQs' },
  { key: 'quotations', label: 'Quotations' },
  { key: 'pos', label: 'POs' },
  { key: 'grns', label: 'GRNs' },
  { key: 'invoices', label: 'Invoices' },
  { key: 'payments', label: 'Payments' },
]

export function ProcurementPage() {
  const { projectId } = useParams()
  const pid = projectId!
  const [tab, setTab] = useState<string>('summary')
  const { canEditProcurement } = useProjectPermissions(projectId)
  const { addRFQItem, deleteRFQItem, addQuotationItem, deleteQuotationItem, addPOItem, deletePOItem, addGRNItem, deleteGRNItem } = useItemActions()
  const { data: project } = useProject(projectId)

  const { data: summary, isLoading: loadingSummary } = useProcurementSummary(projectId)
  const { data: suppliers, isLoading: loadingSuppliers } = useSuppliers()
  const { data: rfqs, isLoading: loadingRFQs } = useRFQs(projectId)
  const { data: quotations, isLoading: loadingQuotations } = useQuotations(projectId)
  const { data: orders, isLoading: loadingOrders } = usePurchaseOrders(projectId)
  const { data: grns, isLoading: loadingGRNs } = useGoodsReceipts(projectId)
  const { data: invoices, isLoading: loadingInvoices } = useProcurementInvoices(projectId)
  const { data: payments, isLoading: loadingPayments } = useProcurementPayments(projectId)

  const [showAddRFQ, setShowAddRFQ] = useState(false)
  const [showAddQuotation, setShowAddQuotation] = useState(false)
  const [showAddPO, setShowAddPO] = useState(false)
  const [showAddGRN, setShowAddGRN] = useState(false)
  const [showAddInvoice, setShowAddInvoice] = useState(false)
  const [showAddPayment, setShowAddPayment] = useState(false)
  const [expandedRow, setExpandedRow] = useState<string | null>(null)
  const toggleRow = (id: string) => setExpandedRow(expandedRow === id ? null : id)
  const poStatusColor = (status: string) => {
    if (status === 'delivered') return '#22c55e'
    if (status === 'cancelled') return '#ef4444'
    if (status === 'partially_delivered') return '#f97316'
    if (status === 'issued') return '#3b82f6'
    return '#f59e0b'
  }
  const invoiceStatusColor = (status: string) => {
    if (status === 'paid') return '#22c55e'
    if (status === 'disputed') return '#ef4444'
    if (status === 'approved') return '#3b82f6'
    return '#f59e0b'
  }

  /* ---- column definitions ---- */

  const supplierColumns = [
    { key: 'code', header: 'Code', width: '90px', render: (s: SupplierData) => <span className="font-mono text-xs text-bp-accent">{s.code}</span> },
    { key: 'name', header: 'Name', render: (s: SupplierData) => <span className="font-medium text-bp-text">{s.name}</span> },
    { key: 'contact_person', header: 'Contact', render: (s: SupplierData) => <span className="text-xs text-bp-muted">{s.contact_person || '-'}</span> },
    { key: 'phone', header: 'Phone', width: '120px', render: (s: SupplierData) => <span className="text-xs text-bp-muted">{s.phone || '-'}</span> },
    { key: 'email', header: 'Email', render: (s: SupplierData) => <span className="text-xs text-bp-muted">{s.email || '-'}</span> },
    { key: 'category', header: 'Category', width: '100px', render: (s: SupplierData) => <span className="text-xs text-bp-muted">{s.category || '-'}</span> },
    { key: 'status', header: 'Status', width: '90px', render: (s: SupplierData) => {
      const color = s.status === 'active' ? '#22c55e' : s.status === 'blacklisted' ? '#ef4444' : '#94a3b8'
      return <StatusBadge text={s.status_display} color={color} />
    }},
  ]

  const rfqColumns = [
    { key: 'code', header: 'Code', width: '90px', render: (r: RFQData) => <span className="font-mono text-xs text-bp-accent">{r.code}</span> },
    { key: 'title', header: 'Title', render: (r: RFQData) => <span className="font-medium text-bp-text">{r.title}</span> },
    { key: 'due_date', header: 'Due Date', width: '100px', render: (r: RFQData) => <span className="text-xs text-bp-muted">{r.due_date || '-'}</span> },
    { key: 'items_count', header: 'Items', width: '60px', render: (r: RFQData) => <span className="text-xs text-bp-muted">{r.items_count}</span> },
    { key: 'status', header: 'Status', render: (r: RFQData) => {
      const color = r.status === 'closed' ? '#22c55e' : r.status === 'issued' ? '#3b82f6' : r.status === 'cancelled' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={r.status_display} color={color} />
    }},
  ]

  const quotationColumns = [
    { key: 'code', header: 'Code', width: '90px', render: (q: QuotationData) => <span className="font-mono text-xs text-bp-accent">{q.code}</span> },
    { key: 'supplier_name', header: 'Supplier', render: (q: QuotationData) => <span className="font-medium text-bp-text">{q.supplier_name || '-'}</span> },
    { key: 'rfq_code', header: 'RFQ', width: '90px', render: (q: QuotationData) => <span className="text-xs text-bp-muted">{q.rfq_code || '-'}</span> },
    { key: 'quote_date', header: 'Quote Date', width: '100px', render: (q: QuotationData) => <span className="text-xs text-bp-muted">{q.quote_date}</span> },
    { key: 'total_amount', header: 'Total', render: (q: QuotationData) => <span className="font-mono text-xs font-semibold text-bp-warning">{formatUGX(parseFloat(q.total_amount))}</span> },
    { key: 'status', header: 'Status', render: (q: QuotationData) => {
      const color = q.status === 'accepted' ? '#22c55e' : q.status === 'rejected' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={q.status_display} color={color} />
    }},
  ]

  const poColumns = [
    { key: 'code', header: 'PO Code', width: '90px', render: (po: PurchaseOrderData) => <span className="font-mono text-xs text-bp-accent">{po.code}</span> },
    { key: 'supplier_name', header: 'Supplier', render: (po: PurchaseOrderData) => <span className="font-medium text-bp-text">{po.supplier_name || '-'}</span> },
    { key: 'order_date', header: 'Order Date', width: '100px', render: (po: PurchaseOrderData) => <span className="text-xs text-bp-muted">{po.order_date}</span> },
    { key: 'delivery_date', header: 'Delivery', width: '100px', render: (po: PurchaseOrderData) => <span className="text-xs text-bp-muted">{po.delivery_date || '-'}</span> },
    { key: 'total_amount', header: 'Total', render: (po: PurchaseOrderData) => <span className="font-mono text-xs font-semibold text-bp-warning">{formatUGX(parseFloat(po.total_amount))}</span> },
    { key: 'status', header: 'Status', render: (po: PurchaseOrderData) => {
      const color = po.status === 'delivered' ? '#22c55e' : po.status === 'issued' ? '#3b82f6' : po.status === 'cancelled' ? '#ef4444' : po.status === 'partially_delivered' ? '#f97316' : '#f59e0b'
      return <StatusBadge text={po.status_display} color={color} />
    }},
  ]

  const grnColumns = [
    { key: 'code', header: 'GRN Code', width: '90px', render: (g: GoodsReceiptData) => <span className="font-mono text-xs text-bp-accent">{g.code}</span> },
    { key: 'receipt_date', header: 'Receipt Date', width: '100px', render: (g: GoodsReceiptData) => <span className="text-xs text-bp-muted">{g.receipt_date}</span> },
    { key: 'received_by_name', header: 'Received By', render: (g: GoodsReceiptData) => <span className="text-xs text-bp-text">{g.received_by_name || '-'}</span> },
    { key: 'status', header: 'Status', render: (g: GoodsReceiptData) => {
      const color = g.status === 'confirmed' ? '#22c55e' : g.status === 'disputed' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={g.status_display} color={color} />
    }},
  ]

  const invoiceColumns = [
    { key: 'code', header: 'Invoice Code', width: '100px', render: (inv: ProcurementInvoiceData) => <span className="font-mono text-xs text-bp-accent">{inv.code}</span> },
    { key: 'supplier_name', header: 'Supplier', render: (inv: ProcurementInvoiceData) => <span className="font-medium text-bp-text">{inv.supplier_name || '-'}</span> },
    { key: 'invoice_date', header: 'Invoice Date', width: '100px', render: (inv: ProcurementInvoiceData) => <span className="text-xs text-bp-muted">{inv.invoice_date}</span> },
    { key: 'due_date', header: 'Due Date', width: '100px', render: (inv: ProcurementInvoiceData) => <span className="text-xs text-bp-muted">{inv.due_date}</span> },
    { key: 'amount', header: 'Amount', render: (inv: ProcurementInvoiceData) => <span className="font-mono text-xs font-semibold text-bp-warning">{formatUGX(parseFloat(inv.amount))}</span> },
    { key: 'status', header: 'Status', render: (inv: ProcurementInvoiceData) => {
      const color = inv.status === 'paid' ? '#22c55e' : inv.status === 'disputed' ? '#ef4444' : inv.status === 'approved' ? '#3b82f6' : '#f59e0b'
      return <StatusBadge text={inv.status_display} color={color} />
    }},
  ]

  const paymentColumns = [
    { key: 'reference', header: 'Reference', width: '100px', render: (p: ProcurementPaymentData) => <span className="font-mono text-xs text-bp-accent">{p.reference || '-'}</span> },
    { key: 'supplier_name', header: 'Supplier', render: (p: ProcurementPaymentData) => <span className="font-medium text-bp-text">{p.supplier_name || '-'}</span> },
    { key: 'payment_date', header: 'Date', width: '100px', render: (p: ProcurementPaymentData) => <span className="text-xs text-bp-muted">{p.payment_date}</span> },
    { key: 'method_display', header: 'Method', width: '90px', render: (p: ProcurementPaymentData) => <span className="text-xs text-bp-muted">{p.method_display}</span> },
    { key: 'amount', header: 'Amount', render: (p: ProcurementPaymentData) => <span className="font-mono text-xs font-semibold text-bp-warning">{formatUGX(parseFloat(p.amount))}</span> },
    { key: 'status', header: 'Status', render: (p: ProcurementPaymentData) => {
      const color = p.status === 'completed' ? '#22c55e' : p.status === 'failed' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={p.status_display} color={color} />
    }},
  ]

  return (
    <div>
      <PageHeader title="Procurement" icon="&#128230;">
        {canEditProcurement && tab === 'rfqs' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddRFQ(true)}>+ RFQ</ActionButton>
        )}
        {canEditProcurement && tab === 'quotations' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddQuotation(true)}>+ Quotation</ActionButton>
        )}
        {canEditProcurement && tab === 'pos' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddPO(true)}>+ Purchase Order</ActionButton>
        )}
        {canEditProcurement && tab === 'grns' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddGRN(true)}>+ GRN</ActionButton>
        )}
        {canEditProcurement && tab === 'invoices' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddInvoice(true)}>+ Invoice</ActionButton>
        )}
        {canEditProcurement && tab === 'payments' && (
          <ActionButton variant="green" size="sm" onClick={() => setShowAddPayment(true)}>+ Payment</ActionButton>
        )}
      </PageHeader>

      <Tabs tabs={TABS} active={tab} onChange={setTab} />

      {/* Summary tab */}
      {tab === 'summary' && (
        loadingSummary ? <LoadingState rows={4} /> :
        summary ? (
          <div className="mt-4 grid gap-4">
            <div className="grid grid-cols-[repeat(auto-fit,minmax(140px,1fr))] gap-2.5">
              <CostCard label="Total POs" value={String(summary.total_pos)} color="#3b82f6" />
              <CostCard label="PO Value" value={formatUGX(summary.total_po_value)} color="#f59e0b" />
              <CostCard label="Pending Delivery" value={String(summary.pending_deliveries)} color="#f97316" />
              <CostCard label="Unpaid Invoices" value={String(summary.unpaid_invoices_count)} color="#ef4444" />
              <CostCard label="Total Invoiced" value={formatUGX(summary.total_invoiced)} color="#a855f7" />
              <CostCard label="Total Paid" value={formatUGX(summary.total_paid)} color="#22c55e" />
              <CostCard label="Outstanding" value={formatUGX(summary.outstanding)} color="#ef4444" />
            </div>

            <div className="grid gap-4 lg:grid-cols-2">
              <DashboardPanel title="Recent Purchase Orders">
                {summary.recent_pos.length > 0 ? (
                  <div className="grid gap-2">
                    {summary.recent_pos.map(po => (
                      <div key={po.id} className="flex items-center justify-between border-b border-bp-border pb-2 last:border-b-0 last:pb-0">
                        <div className="min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="font-mono text-[11px] font-bold text-bp-accent">{po.code}</span>
                            <span className="truncate text-[11px] text-bp-muted">{po.supplier_name || '-'}</span>
                          </div>
                          <div className="mt-1 text-[10px] text-bp-muted">{formatDate(po.order_date)}</div>
                        </div>
                        <div className="text-right">
                          <StatusBadge text={po.status_display} color={poStatusColor(po.status)} />
                          <div className="mt-1 font-mono text-[11px] text-bp-text">{formatUGX(po.total_amount)}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <DashboardEmpty text="No purchase orders yet." />
                )}
              </DashboardPanel>

              <DashboardPanel title="Unpaid Invoices">
                {summary.unpaid_invoices.length > 0 ? (
                  <div className="grid gap-2">
                    {summary.unpaid_invoices.map(invoice => (
                      <div key={invoice.id} className="flex items-center justify-between border-b border-bp-border pb-2 last:border-b-0 last:pb-0">
                        <div className="min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="font-mono text-[11px] font-bold text-bp-danger">{invoice.code}</span>
                            <span className="truncate text-[11px] text-bp-muted">{invoice.supplier_name || '-'}</span>
                          </div>
                          <div className="mt-1 text-[10px] text-bp-danger">Due: {invoice.due_date ? formatDate(invoice.due_date) : '-'}</div>
                        </div>
                        <div className="text-right">
                          <StatusBadge text={invoice.status_display} color={invoiceStatusColor(invoice.status)} />
                          <div className="mt-1 font-mono text-[11px] text-bp-text">{formatUGX(invoice.amount)}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <DashboardEmpty text="No unpaid invoices." />
                )}
              </DashboardPanel>

              <DashboardPanel title="Workflow">
                <div className="flex flex-wrap items-center gap-2 text-[11px]">
                  {[
                    { label: `RFQ (${summary.workflow_counts.rfqs})`, color: '#3b82f6' },
                    { label: `Quotes (${summary.workflow_counts.quotations})`, color: '#f59e0b' },
                    { label: `PO (${summary.workflow_counts.pos})`, color: '#22c55e' },
                    { label: `GRN (${summary.workflow_counts.grns})`, color: '#f97316' },
                    { label: `Invoice (${summary.workflow_counts.invoices})`, color: '#ef4444' },
                    { label: `Payment (${summary.workflow_counts.payments})`, color: '#10b981' },
                  ].map((step, idx) => (
                    <div key={step.label} className="flex items-center gap-2">
                      {idx > 0 && <span className="text-bp-muted">&rarr;</span>}
                      <span className="rounded-full border px-3 py-1 font-semibold" style={{ color: step.color, borderColor: `${step.color}66`, backgroundColor: `${step.color}22` }}>
                        {step.label}
                      </span>
                    </div>
                  ))}
                </div>
              </DashboardPanel>

              <DashboardPanel title="Top Suppliers">
                {summary.top_suppliers.length > 0 ? (
                  <div className="grid gap-2">
                    {summary.top_suppliers.map(supplier => (
                      <div key={supplier.supplier_name} className="flex items-center justify-between border-b border-bp-border pb-2 last:border-b-0 last:pb-0">
                        <div className="min-w-0">
                          <div className="truncate text-[11px] text-bp-text">{supplier.supplier_name}</div>
                          <div className="mt-1 text-[10px] text-bp-muted">{supplier.po_count} purchase order{supplier.po_count === 1 ? '' : 's'}</div>
                        </div>
                        <div className="font-mono text-[11px] text-bp-accent">{formatUGX(supplier.total_value)}</div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <DashboardEmpty text="Supplier rankings will appear once POs are raised." />
                )}
              </DashboardPanel>
            </div>
          </div>
        ) : <EmptyState icon="&#128230;" title="No summary data" description="Procurement summary will appear once data is available." />
      )}

      {/* Suppliers tab */}
      {tab === 'suppliers' && (
        loadingSuppliers ? <LoadingState rows={4} /> :
        (suppliers && suppliers.length > 0) ? (
          <DataTable columns={supplierColumns} data={suppliers} emptyText="No suppliers" />
        ) : <EmptyState icon="&#128230;" title="No suppliers" description="Suppliers will appear here once added to the system." />
      )}

      {/* RFQs tab */}
      {tab === 'rfqs' && (
        loadingRFQs ? <LoadingState rows={4} /> :
        (rfqs && rfqs.length > 0) ? (
          <div className="grid gap-1.5">
            <DataTable columns={rfqColumns} data={rfqs} emptyText="No RFQs"
              onRowClick={(r: RFQData) => toggleRow(r.id)}
              renderExpanded={(r: RFQData) => expandedRow === r.id ? (
                <ItemsPanel
                  items={r.items.map(i => ({ id: i.id, description: i.description, unit: i.unit, qty: i.quantity, price: '', total: '' }))}
                  showPrice={false}
                  onAdd={canEditProcurement ? (d) => addRFQItem(pid, r.id, d) : undefined}
                  onDelete={canEditProcurement ? (itemId) => deleteRFQItem(pid, r.id, itemId) : undefined}
                />
              ) : null}
            />
          </div>
        ) : <EmptyState icon="&#128230;" title="No RFQs" description="Create an RFQ to start the procurement process." />
      )}

      {/* Quotations tab */}
      {tab === 'quotations' && (
        loadingQuotations ? <LoadingState rows={4} /> :
        (quotations && quotations.length > 0) ? (
          <DataTable columns={quotationColumns} data={quotations} emptyText="No quotations"
            onRowClick={(r: QuotationData) => toggleRow(r.id)}
            renderExpanded={(r: QuotationData) => expandedRow === r.id ? (
              <ItemsPanel
                items={r.items.map(i => ({ id: i.id, description: i.description, unit: i.unit, qty: i.quantity, price: i.unit_price, total: i.line_total }))}
                showPrice={true}
                onAdd={canEditProcurement ? (d) => addQuotationItem(pid, r.id, d) : undefined}
                onDelete={canEditProcurement ? (itemId) => deleteQuotationItem(pid, r.id, itemId) : undefined}
              />
            ) : null}
          />
        ) : <EmptyState icon="&#128230;" title="No quotations" description="Add quotations received from suppliers." />
      )}

      {/* POs tab */}
      {tab === 'pos' && (
        loadingOrders ? <LoadingState rows={4} /> :
        (orders && orders.length > 0) ? (
          <DataTable columns={poColumns} data={orders} emptyText="No purchase orders"
            onRowClick={(r: PurchaseOrderData) => toggleRow(r.id)}
            renderExpanded={(r: PurchaseOrderData) => expandedRow === r.id ? (
              <PODetailPanel
                po={r}
                projectName={project?.name || 'Project'}
                onAddItem={canEditProcurement ? (d) => addPOItem(pid, r.id, d) : undefined}
                onDeleteItem={canEditProcurement ? (itemId) => deletePOItem(pid, r.id, itemId) : undefined}
              />
            ) : null}
          />
        ) : <EmptyState icon="&#128230;" title="No purchase orders" description="Create a purchase order to start tracking procurement." />
      )}

      {/* GRNs tab */}
      {tab === 'grns' && (
        loadingGRNs ? <LoadingState rows={4} /> :
        (grns && grns.length > 0) ? (
          <DataTable columns={grnColumns} data={grns} emptyText="No goods receipts"
            onRowClick={(r: GoodsReceiptData) => toggleRow(r.id)}
            renderExpanded={(r: GoodsReceiptData) => expandedRow === r.id ? (
              <ItemsPanel
                items={r.items.map(i => ({ id: i.id, description: i.description, unit: i.unit, qty: i.received_quantity, price: i.ordered_quantity, total: '' }))}
                showPrice={false}
                priceLabel="Ordered"
                qtyLabel="Received"
                onAdd={canEditProcurement ? (d) => addGRNItem(pid, r.id, d) : undefined}
                onDelete={canEditProcurement ? (itemId) => deleteGRNItem(pid, r.id, itemId) : undefined}
              />
            ) : null}
          />
        ) : <EmptyState icon="&#128230;" title="No goods receipts" description="Record goods receipts against purchase orders." />
      )}

      {/* Invoices tab */}
      {tab === 'invoices' && (
        loadingInvoices ? <LoadingState rows={4} /> :
        (invoices && invoices.length > 0) ? (
          <DataTable columns={invoiceColumns} data={invoices} emptyText="No invoices" />
        ) : <EmptyState icon="&#128230;" title="No invoices" description="Record supplier invoices for tracking." />
      )}

      {/* Payments tab */}
      {tab === 'payments' && (
        loadingPayments ? <LoadingState rows={4} /> :
        (payments && payments.length > 0) ? (
          <DataTable columns={paymentColumns} data={payments} emptyText="No payments" />
        ) : <EmptyState icon="&#128230;" title="No payments" description="Record payments made to suppliers." />
      )}

      {/* Modals */}
      {showAddRFQ && <AddRFQModal projectId={pid} onClose={() => setShowAddRFQ(false)} />}
      {showAddQuotation && <AddQuotationModal projectId={pid} onClose={() => setShowAddQuotation(false)} />}
      {showAddPO && <AddPOModal projectId={pid} projectLocation={project?.location || ''} onClose={() => setShowAddPO(false)} />}
      {showAddGRN && <AddGRNModal projectId={pid} onClose={() => setShowAddGRN(false)} />}
      {showAddInvoice && <AddInvoiceModal projectId={pid} onClose={() => setShowAddInvoice(false)} />}
      {showAddPayment && <AddPaymentModal projectId={pid} onClose={() => setShowAddPayment(false)} />}
    </div>
  )
}

function DashboardPanel({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="rounded-lg border border-bp-border bg-bp-card p-4">
      <h3 className="mb-3 text-sm font-semibold text-bp-accent">{title}</h3>
      {children}
    </div>
  )
}

function DashboardEmpty({ text }: { text: string }) {
  return <div className="text-xs text-bp-muted">{text}</div>
}

function escapeHtml(value: string | number | null | undefined) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function formatPOFigure(value: string | number) {
  const numeric = typeof value === 'number' ? value : Number.parseFloat(value || '0')
  if (!Number.isFinite(numeric)) return '0'
  return numeric.toLocaleString(undefined, { maximumFractionDigits: 2 })
}

function buildPurchaseOrderDocument(po: PurchaseOrderData, projectName: string) {
  const css = [
    'body{font-family:Calibri;padding:30px;max-width:800px;margin:auto}',
    'h1{color:#f59e0b;border-bottom:3px solid #f59e0b;padding-bottom:8px}',
    'h2{color:#3b82f6;margin-top:16px}',
    'table{width:100%;border-collapse:collapse;margin:10px 0}',
    'th{background:#0f172a;color:#f59e0b;padding:6px 10px;font-size:10px;text-align:left}',
    'td{padding:5px 10px;border:1px solid #ddd;font-size:11px}',
    '.row{display:flex;gap:16px;margin-bottom:4px}',
    '.label{color:#666;width:150px;font-size:11px}',
    '.val{font-weight:600;font-size:11px}',
    '.foot{margin-top:20px;color:#999;font-size:9px;text-align:center}',
    '@media print{@page{size:A4;margin:15mm}}',
  ].join('')

  const itemRows = po.items.map(item => (
    `<tr><td>${escapeHtml(item.description)}</td><td>${escapeHtml(item.quantity)}</td><td>${escapeHtml(item.unit)}</td><td>UGX ${formatPOFigure(item.unit_price)}</td><td>UGX ${formatPOFigure(item.line_total)}</td></tr>`
  )).join('')

  return [
    '<!DOCTYPE html><html><head><meta charset="utf-8"><style>',
    css,
    '</style></head><body>',
    '<h1>Purchase Order</h1>',
    `<div class="row"><span class="label">PO Number:</span><span class="val" style="font-size:16px;color:#f59e0b">${escapeHtml(po.code)}</span></div>`,
    `<div class="row"><span class="label">Date:</span><span class="val">${escapeHtml(po.order_date)}</span></div>`,
    `<div class="row"><span class="label">Project:</span><span class="val">${escapeHtml(projectName)}</span></div>`,
    `<div class="row"><span class="label">Supplier:</span><span class="val">${escapeHtml(po.supplier_name || '')}</span></div>`,
    `<div class="row"><span class="label">Delivery To:</span><span class="val">${escapeHtml(po.delivery_address)}</span></div>`,
    `<div class="row"><span class="label">Delivery Date:</span><span class="val">${escapeHtml(po.delivery_date || 'TBD')}</span></div>`,
    `<div class="row"><span class="label">Payment Terms:</span><span class="val">${escapeHtml(po.payment_terms)}</span></div>`,
    '<h2>Items</h2>',
    '<table><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Total</th></tr>',
    itemRows,
    '</table>',
    `<div style="text-align:right;margin-top:10px;font-size:14px"><strong>Total: UGX ${formatPOFigure(po.total_amount)}</strong></div>`,
    `<div class="foot">${escapeHtml(projectName)} | Generated by BuildPro - ${escapeHtml(new Date().toLocaleString())}</div>`,
    '</body></html>',
  ].join('')
}

function downloadPurchaseOrder(po: PurchaseOrderData, projectName: string, format: 'word' | 'pdf') {
  const html = buildPurchaseOrderDocument(po, projectName)
  if (format === 'word') {
    downloadText(`\uFEFF${html}`, `BuildPro_${po.code}.doc`, 'application/msword;charset=utf-8')
    return
  }
  // Prototype "PDF" export is a print-ready HTML file.
  downloadText(html, `BuildPro_${po.code}.html`, 'text/html;charset=utf-8')
}

function PODetailPanel({
  po,
  projectName,
  onAddItem,
  onDeleteItem,
}: {
  po: PurchaseOrderData
  projectName: string
  onAddItem?: (d: ItemPayload) => Promise<void>
  onDeleteItem?: (itemId: number) => Promise<void>
}) {
  const { showToast } = useUIStore()

  return (
    <div className="border-t border-bp-border bg-[#0d1526]" onClick={(e) => e.stopPropagation()}>
      <div className="grid gap-4 px-4 py-3 md:grid-cols-[1.35fr_auto] md:items-start">
        <div className="grid gap-2 sm:grid-cols-2">
          <MetaRow label="PO Number" value={po.code} accent />
          <MetaRow label="Date" value={po.order_date} />
          <MetaRow label="Supplier" value={po.supplier_name || '-'} />
          <MetaRow label="Delivery To" value={po.delivery_address || '-'} />
          <MetaRow label="Delivery Date" value={po.delivery_date || 'TBD'} />
          <MetaRow label="Payment Terms" value={po.payment_terms || '-'} />
          <MetaRow label="Status" value={po.status_display} />
          <MetaRow label="Total" value={formatUGX(parseFloat(po.total_amount))} accent />
          {po.instructions && <MetaRow label="Special Instructions" value={po.instructions} fullWidth />}
        </div>

        <div className="flex flex-wrap gap-2 md:justify-end">
          <ActionButton
            variant="blue"
            size="sm"
            onClick={() => {
              downloadPurchaseOrder(po, projectName, 'word')
              showToast(`${po.code} downloaded as Word`, 'success')
            }}
          >
            &#11015; Word
          </ActionButton>
          <ActionButton
            variant="blue"
            size="sm"
            onClick={() => {
              downloadPurchaseOrder(po, projectName, 'pdf')
              showToast(`${po.code} downloaded in prototype PDF format`, 'success')
            }}
          >
            &#11015; PDF
          </ActionButton>
        </div>
      </div>

      <ItemsPanel
        items={po.items.map(i => ({ id: i.id, description: i.description, unit: i.unit, qty: i.quantity, price: i.unit_price, total: i.line_total }))}
        showPrice={true}
        onAdd={onAddItem}
        onDelete={onDeleteItem}
      />
    </div>
  )
}

function MetaRow({
  label,
  value,
  accent,
  fullWidth,
}: {
  label: string
  value: string
  accent?: boolean
  fullWidth?: boolean
}) {
  return (
    <div className={fullWidth ? 'sm:col-span-2' : ''}>
      <div className="mb-1 text-[10px] uppercase tracking-wider text-bp-muted">{label}</div>
      <div className={accent ? 'font-mono text-sm font-semibold text-bp-accent' : 'text-sm text-bp-text'}>{value}</div>
    </div>
  )
}

/* ------------------------------------------------------------------ */
/* Item panel helpers (used for add/delete mutations inline)            */
/* ------------------------------------------------------------------ */

type ItemPayload = Record<string, unknown>

function useItemActions() {
  const qc = useQueryClient()
  const { showToast } = useUIStore()

  const postItem = async (url: string, d: ItemPayload, key: string[]) => {
    await api.post(url, d)
    qc.invalidateQueries({ queryKey: key })
    showToast('Item added', 'success')
  }
  const removeItem = async (url: string, key: string[]) => {
    await api.delete(url)
    qc.invalidateQueries({ queryKey: key })
    showToast('Item removed', 'success')
  }

  const addRFQItem = (pid: string, rid: string, d: ItemPayload) => postItem(`/procurement/${pid}/rfqs/${rid}/items/`, d, ['procurement', pid, 'rfqs'])
  const deleteRFQItem = (pid: string, rid: string, iid: number) => removeItem(`/procurement/${pid}/rfqs/${rid}/items/${iid}/`, ['procurement', pid, 'rfqs'])
  const addQuotationItem = (pid: string, qid: string, d: ItemPayload) => postItem(`/procurement/${pid}/quotations/${qid}/items/`, d, ['procurement', pid, 'quotations'])
  const deleteQuotationItem = (pid: string, qid: string, iid: number) => removeItem(`/procurement/${pid}/quotations/${qid}/items/${iid}/`, ['procurement', pid, 'quotations'])
  const addPOItem = (pid: string, oid: string, d: ItemPayload) => postItem(`/procurement/${pid}/purchase-orders/${oid}/items/`, d, ['procurement', pid, 'purchase-orders'])
  const deletePOItem = (pid: string, oid: string, iid: number) => removeItem(`/procurement/${pid}/purchase-orders/${oid}/items/${iid}/`, ['procurement', pid, 'purchase-orders'])
  const addGRNItem = (pid: string, gid: string, d: ItemPayload) => postItem(`/procurement/${pid}/goods-receipts/${gid}/items/`, d, ['procurement', pid, 'goods-receipts'])
  const deleteGRNItem = (pid: string, gid: string, iid: number) => removeItem(`/procurement/${pid}/goods-receipts/${gid}/items/${iid}/`, ['procurement', pid, 'goods-receipts'])

  return { addRFQItem, deleteRFQItem, addQuotationItem, deleteQuotationItem, addPOItem, deletePOItem, addGRNItem, deleteGRNItem }
}

/* ------------------------------------------------------------------ */
/* Items Panel -- inline expandable item list for procurement records   */
/* ------------------------------------------------------------------ */

interface ItemRow { id: number | string; description: string; unit: string; qty: string; price: string; total: string }

function ItemsPanel({ items, showPrice, priceLabel, qtyLabel, onAdd, onDelete }: {
  items: ItemRow[]
  showPrice: boolean
  priceLabel?: string
  qtyLabel?: string
  onAdd?: (d: ItemPayload) => Promise<void>
  onDelete?: (itemId: number) => Promise<void>
}) {
  const [adding, setAdding] = useState(false)
  const [desc, setDesc] = useState('')
  const [unit, setUnit] = useState('unit')
  const [qty, setQty] = useState('')
  const [price, setPrice] = useState('')
  const { showToast } = useUIStore()

  return (
    <div className="border-t border-bp-border bg-[#0d1526] px-4 py-3" onClick={(e) => e.stopPropagation()}>
      <div className="mb-2 flex items-center justify-between">
        <span className="text-[11px] font-semibold uppercase tracking-wider text-bp-muted">Line Items ({items.length})</span>
        {onAdd && !adding && (
          <ActionButton variant="blue" size="sm" onClick={() => setAdding(true)}>+ Add Item</ActionButton>
        )}
      </div>
      {items.length > 0 ? (
        <table className="w-full text-xs">
          <thead>
            <tr className="text-left text-bp-muted">
              <th className="pb-1 pr-2">#</th>
              <th className="pb-1 pr-2">Description</th>
              <th className="pb-1 pr-2 w-[60px]">Unit</th>
              <th className="pb-1 pr-2 w-[70px]">{qtyLabel || 'Qty'}</th>
              {showPrice && <th className="pb-1 pr-2 w-[90px]">{priceLabel || 'Unit Price'}</th>}
              {showPrice && <th className="pb-1 pr-2 w-[100px]">Total</th>}
              {onDelete && <th className="pb-1 w-[40px]"></th>}
            </tr>
          </thead>
          <tbody>
            {items.map((item, idx) => (
              <tr key={item.id} className="border-t border-bp-border/50">
                <td className="py-1 pr-2 text-bp-muted">{idx + 1}</td>
                <td className="py-1 pr-2 text-bp-text">{item.description}</td>
                <td className="py-1 pr-2 text-bp-muted">{item.unit}</td>
                <td className="py-1 pr-2 font-mono text-bp-info">{item.qty}</td>
                {showPrice && <td className="py-1 pr-2 font-mono text-bp-muted">{item.price}</td>}
                {showPrice && <td className="py-1 pr-2 font-mono font-semibold text-bp-warning">{item.total ? formatUGX(parseFloat(item.total)) : '-'}</td>}
                {onDelete && (
                  <td className="py-1">
                    <button className="text-bp-muted hover:text-bp-danger text-[10px]" onClick={() => onDelete(Number(item.id))}>&#10005;</button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p className="text-[11px] text-bp-muted">No line items yet.</p>
      )}
      {adding && (
        <div className="mt-2 grid grid-cols-[1fr_60px_70px_auto] gap-1.5 items-end">
          <input className="text-xs" placeholder="Description" value={desc} onChange={(e) => setDesc(e.target.value)} autoFocus />
          <input className="text-xs" placeholder="Unit" value={unit} onChange={(e) => setUnit(e.target.value)} />
          <input className="text-xs" type="number" placeholder="Qty" value={qty} onChange={(e) => setQty(e.target.value)} />
          {showPrice && <input className="text-xs w-[80px]" type="number" placeholder="Price" value={price} onChange={(e) => setPrice(e.target.value)} />}
          <div className="flex gap-1">
            <ActionButton variant="green" size="sm" onClick={async () => {
              if (!desc || !qty) { showToast('Description and quantity required', 'warning'); return }
              const payload: Record<string, unknown> = { description: desc, unit, quantity: parseFloat(qty) }
              if (showPrice && price) payload.unit_price = parseFloat(price)
              if (!showPrice && price) payload.received_quantity = parseFloat(qty)
              await onAdd!(payload)
              setDesc(''); setQty(''); setPrice(''); setAdding(false)
            }}>Save</ActionButton>
            <ActionButton variant="ghost" size="sm" onClick={() => setAdding(false)}>Cancel</ActionButton>
          </div>
        </div>
      )}
    </div>
  )
}

/* ------------------------------------------------------------------ */
/* Add RFQ Modal                                                       */
/* ------------------------------------------------------------------ */

function AddRFQModal({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [dueDate, setDueDate] = useState('')
  const create = useCreateRFQ(projectId)
  const { showToast } = useUIStore()

  return (
    <Modal open={true} onClose={onClose} title="Create RFQ" width={420}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Title *</label>
          <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="RFQ title" />
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Description</label>
          <textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="RFQ description..." rows={3} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Due Date</label>
          <input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!title) { showToast('Title is required', 'warning'); return }
          await create.mutateAsync({ title, description: description || undefined, due_date: dueDate || undefined })
          showToast('RFQ created', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Creating...' : 'Create RFQ'}</ActionButton>
      </div>
    </Modal>
  )
}

/* ------------------------------------------------------------------ */
/* Add Quotation Modal                                                 */
/* ------------------------------------------------------------------ */

function AddQuotationModal({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [supplier, setSupplier] = useState('')
  const [quoteDate, setQuoteDate] = useState(new Date().toISOString().slice(0, 10))
  const [notes, setNotes] = useState('')
  const { data: suppliers, isLoading: loadingSuppliers } = useSuppliers()
  const create = useCreateQuotation(projectId)
  const { showToast } = useUIStore()

  return (
    <Modal open={true} onClose={onClose} title="Add Quotation" width={420}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Supplier *</label>
          {loadingSuppliers ? (
            <select disabled><option>Loading suppliers...</option></select>
          ) : (
            <select value={supplier} onChange={(e) => setSupplier(e.target.value)}>
              <option value="">-- Select supplier --</option>
              {(suppliers || []).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          )}
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Quote Date *</label>
          <input type="date" value={quoteDate} onChange={(e) => setQuoteDate(e.target.value)} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Notes</label>
          <textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Additional notes..." rows={3} />
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!supplier) { showToast('Please select a supplier', 'warning'); return }
          await create.mutateAsync({ supplier, quote_date: quoteDate || undefined, notes: notes || undefined })
          showToast('Quotation added', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Adding...' : 'Add Quotation'}</ActionButton>
      </div>
    </Modal>
  )
}

/* ------------------------------------------------------------------ */
/* Add PO Modal                                                        */
/* ------------------------------------------------------------------ */

function AddPOModal({
  projectId,
  projectLocation,
  onClose,
}: {
  projectId: string
  projectLocation: string
  onClose: () => void
}) {
  const [supplier, setSupplier] = useState('')
  const [deliveryAddress, setDeliveryAddress] = useState(projectLocation)
  const [deliveryDate, setDeliveryDate] = useState('')
  const [paymentTerms, setPaymentTerms] = useState('30 days net')
  const [instructions, setInstructions] = useState('')
  const { data: suppliers, isLoading: loadingSuppliers } = useSuppliers()
  const create = useCreatePO(projectId)
  const { showToast } = useUIStore()

  useEffect(() => {
    if (!deliveryAddress && projectLocation) setDeliveryAddress(projectLocation)
  }, [deliveryAddress, projectLocation])

  return (
    <Modal open={true} onClose={onClose} title="Create Purchase Order" width={480}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Supplier *</label>
          {loadingSuppliers ? (
            <select disabled><option>Loading suppliers...</option></select>
          ) : (
            <select value={supplier} onChange={(e) => setSupplier(e.target.value)}>
              <option value="">-- Select supplier --</option>
              {(suppliers || []).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          )}
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Delivery Address</label>
          <input value={deliveryAddress} onChange={(e) => setDeliveryAddress(e.target.value)} placeholder="Site delivery location" />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Delivery Date</label>
            <input type="date" value={deliveryDate} onChange={(e) => setDeliveryDate(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Payment Terms</label>
            <input value={paymentTerms} onChange={(e) => setPaymentTerms(e.target.value)} placeholder="30 days net" />
          </div>
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Special Instructions</label>
          <textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder="Optional delivery or handling instructions..." rows={3} />
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!supplier) { showToast('Please select a supplier', 'warning'); return }
          await create.mutateAsync({
            supplier,
            delivery_address: deliveryAddress || undefined,
            delivery_date: deliveryDate || undefined,
            payment_terms: paymentTerms || undefined,
            instructions: instructions || undefined,
          })
          showToast('Purchase order created', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Creating...' : 'Create PO'}</ActionButton>
      </div>
    </Modal>
  )
}

/* ------------------------------------------------------------------ */
/* Add GRN Modal                                                       */
/* ------------------------------------------------------------------ */

function AddGRNModal({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [purchaseOrder, setPurchaseOrder] = useState('')
  const [receiptDate, setReceiptDate] = useState(new Date().toISOString().slice(0, 10))
  const [notes, setNotes] = useState('')
  const { data: pos, isLoading: loadingPOs } = usePurchaseOrders(projectId)
  const create = useCreateGRN(projectId)
  const { showToast } = useUIStore()

  return (
    <Modal open={true} onClose={onClose} title="Create Goods Receipt" width={420}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Purchase Order *</label>
          {loadingPOs ? (
            <select disabled><option>Loading purchase orders...</option></select>
          ) : (
            <select value={purchaseOrder} onChange={(e) => setPurchaseOrder(e.target.value)}>
              <option value="">-- Select purchase order --</option>
              {(pos || []).map(po => <option key={po.id} value={po.id}>{po.code} - {po.supplier_name || 'Unknown'}</option>)}
            </select>
          )}
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Receipt Date *</label>
          <input type="date" value={receiptDate} onChange={(e) => setReceiptDate(e.target.value)} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Notes</label>
          <textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Additional notes..." rows={3} />
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!purchaseOrder) { showToast('Please select a purchase order', 'warning'); return }
          if (!receiptDate) { showToast('Receipt date is required', 'warning'); return }
          await create.mutateAsync({ purchase_order: purchaseOrder, receipt_date: receiptDate, notes: notes || undefined })
          showToast('Goods receipt created', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Creating...' : 'Create GRN'}</ActionButton>
      </div>
    </Modal>
  )
}

/* ------------------------------------------------------------------ */
/* Add Invoice Modal                                                   */
/* ------------------------------------------------------------------ */

function AddInvoiceModal({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [supplier, setSupplier] = useState('')
  const [amount, setAmount] = useState('')
  const [invoiceDate, setInvoiceDate] = useState(new Date().toISOString().slice(0, 10))
  const [dueDate, setDueDate] = useState('')
  const { data: suppliers, isLoading: loadingSuppliers } = useSuppliers()
  const create = useCreateInvoice(projectId)
  const { showToast } = useUIStore()

  return (
    <Modal open={true} onClose={onClose} title="Create Invoice" width={420}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Supplier *</label>
          {loadingSuppliers ? (
            <select disabled><option>Loading suppliers...</option></select>
          ) : (
            <select value={supplier} onChange={(e) => setSupplier(e.target.value)}>
              <option value="">-- Select supplier --</option>
              {(suppliers || []).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          )}
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Amount (UGX) *</label>
          <input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0" />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Invoice Date *</label>
            <input type="date" value={invoiceDate} onChange={(e) => setInvoiceDate(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Due Date</label>
            <input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
          </div>
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!supplier) { showToast('Please select a supplier', 'warning'); return }
          if (!amount) { showToast('Amount is required', 'warning'); return }
          await create.mutateAsync({
            supplier,
            amount: parseFloat(amount),
            invoice_date: invoiceDate,
            due_date: dueDate || undefined,
          })
          showToast('Invoice created', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Creating...' : 'Create Invoice'}</ActionButton>
      </div>
    </Modal>
  )
}

/* ------------------------------------------------------------------ */
/* Add Payment Modal                                                   */
/* ------------------------------------------------------------------ */

function AddPaymentModal({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [supplier, setSupplier] = useState('')
  const [amount, setAmount] = useState('')
  const [paymentDate, setPaymentDate] = useState(new Date().toISOString().slice(0, 10))
  const [method, setMethod] = useState('')
  const { data: suppliers, isLoading: loadingSuppliers } = useSuppliers()
  const create = useCreatePayment(projectId)
  const { showToast } = useUIStore()

  return (
    <Modal open={true} onClose={onClose} title="Record Payment" width={420}>
      <div className="grid gap-3">
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Supplier *</label>
          {loadingSuppliers ? (
            <select disabled><option>Loading suppliers...</option></select>
          ) : (
            <select value={supplier} onChange={(e) => setSupplier(e.target.value)}>
              <option value="">-- Select supplier --</option>
              {(suppliers || []).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          )}
        </div>
        <div>
          <label className="mb-1 block text-xs font-semibold text-bp-muted">Amount (UGX) *</label>
          <input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0" />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Payment Date *</label>
            <input type="date" value={paymentDate} onChange={(e) => setPaymentDate(e.target.value)} />
          </div>
          <div>
            <label className="mb-1 block text-xs font-semibold text-bp-muted">Method</label>
            <select value={method} onChange={(e) => setMethod(e.target.value)}>
              <option value="">-- Select --</option>
              <option value="bank_transfer">Bank Transfer</option>
              <option value="mobile_money">Mobile Money</option>
              <option value="cheque">Cheque</option>
              <option value="cash">Cash</option>
            </select>
          </div>
        </div>
        <ActionButton variant="green" className="!w-full !mt-1" onClick={async () => {
          if (!supplier) { showToast('Please select a supplier', 'warning'); return }
          if (!amount) { showToast('Amount is required', 'warning'); return }
          await create.mutateAsync({
            supplier,
            amount: parseFloat(amount),
            payment_date: paymentDate,
            method: method || undefined,
          })
          showToast('Payment recorded', 'success'); onClose()
        }} disabled={create.isPending}>{create.isPending ? 'Recording...' : 'Record Payment'}</ActionButton>
      </div>
    </Modal>
  )
}
