import { useParams } from 'react-router-dom'
import { useState } from 'react'
import {
  PageHeader, SectionCard, StatusBadge, ActionButton,
  DataTable, LoadingState, EmptyState,
} from '../../components/ui'
import {
  useAvailableReports, useExportHistory, useGenerateExport, useRedownloadExport,
  type ExportHistoryItem,
} from '../../hooks/useReports'
import { useProjectPermissions } from '../../hooks/useProjectPermissions'
import { useUIStore } from '../../stores/uiStore'

/**
 * Project-level Reports page -- list available reports, generate exports
 * in CSV/Excel/PDF/Word, and view export history.
 */

const FORMAT_LABELS: Record<string, string> = {
  csv: 'CSV',
  xlsx: 'Excel',
  pdf: 'PDF',
  docx: 'Word',
}

const FORMAT_COLORS: Record<string, string> = {
  csv: '#22c55e',
  xlsx: '#3b82f6',
  pdf: '#ef4444',
  docx: '#6366f1',
}

export function ProjectReportsPage() {
  const { projectId } = useParams()
  const pid = projectId!
  const { data: reports, isLoading: loadingReports } = useAvailableReports(projectId)
  const { data: history, isLoading: loadingHistory } = useExportHistory(projectId)
  const { canExportReports } = useProjectPermissions(projectId)
  const generate = useGenerateExport(pid)
  const redownload = useRedownloadExport(pid)
  const { showToast } = useUIStore()
  const [generating, setGenerating] = useState<string | null>(null)

  if (loadingReports) return <LoadingState rows={4} />

  const handleGenerate = async (reportKey: string, format: string) => {
    setGenerating(`${reportKey}-${format}`)
    try {
      await generate.mutateAsync({ report_key: reportKey, format })
      showToast(`${FORMAT_LABELS[format]} exported successfully`, 'success')
    } catch {
      showToast('Export failed', 'error')
    }
    setGenerating(null)
  }

  const historyColumns = [
    { key: 'report', header: 'Report', render: (h: ExportHistoryItem) => <span className="font-medium text-bp-text">{h.report_key_display}</span> },
    { key: 'format', header: 'Format', width: '80px', render: (h: ExportHistoryItem) => <StatusBadge text={h.format_display} color={FORMAT_COLORS[h.format] || '#94a3b8'} /> },
    { key: 'rows', header: 'Rows', width: '60px', render: (h: ExportHistoryItem) => <span className="font-mono text-xs text-bp-muted">{h.row_count}</span> },
    { key: 'file', header: 'File', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{h.file_name}</span> },
    { key: 'by', header: 'Generated By', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{h.created_by_name}</span> },
    { key: 'date', header: 'Date', width: '100px', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{new Date(h.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })}</span> },
    { key: 'status', header: 'Status', width: '80px', render: (h: ExportHistoryItem) => {
      const color = h.status === 'completed' ? '#22c55e' : h.status === 'failed' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={h.status_display} color={color} />
    }},
    { key: 'download', header: '', width: '90px', render: (h: ExportHistoryItem) => (
      h.status === 'completed' && h.download_available ? (
        <ActionButton variant="ghost" size="sm" onClick={() => {
          redownload.mutateAsync(h).catch(() => showToast('Download failed', 'error'))
        }}>Re-download</ActionButton>
      ) : null
    )},
  ]

  return (
    <div>
      <PageHeader title="Reports & Exports" icon="&#128202;" />

      {/* Available Reports Grid */}
      <div className="mb-6 grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-3">
        {(reports || []).map(report => (
          <SectionCard key={report.key}>
            <div className="mb-2 text-sm font-semibold text-bp-text">{report.label}</div>
            <div className="flex flex-wrap gap-1.5">
              {report.formats.map(fmt => (
                <ActionButton
                  key={fmt}
                  variant={fmt === 'pdf' ? 'red' : fmt === 'xlsx' ? 'blue' : fmt === 'docx' ? 'accent' : 'green'}
                  size="sm"
                  onClick={() => handleGenerate(report.key, fmt)}
                  disabled={!canExportReports || generating === `${report.key}-${fmt}`}
                >
                  {generating === `${report.key}-${fmt}` ? 'Generating...' : FORMAT_LABELS[fmt]}
                </ActionButton>
              ))}
            </div>
          </SectionCard>
        ))}
      </div>

      {/* Export History */}
      <div className="mb-2 text-sm font-semibold text-bp-text">Export History</div>
      {loadingHistory ? <LoadingState rows={3} /> :
        (history && history.length > 0) ? (
          <DataTable columns={historyColumns} data={history} emptyText="No exports yet" />
        ) : (
          <EmptyState icon="&#128202;" title="No exports yet" description="Generate a report to see it here." />
        )
      }
    </div>
  )
}
