import { useParams, Link } from 'react-router-dom'
import { useState } from 'react'
import {
  SectionCard, StatusBadge, ActionButton,
  DataTable, LoadingState, EmptyState,
} from '../../components/ui'
import {
  useExportHistory, useRedownloadExport,
  useReportData,
  type ExportHistoryItem,
} from '../../hooks/useReports'
import { useProject } from '../../hooks/useProjects'
import { useUIStore } from '../../stores/uiStore'
import { triggerDownload, downloadText } from '../../lib/download'

/**
 * Project-level Reports page -- prototype-matching layout:
 *   1. Header: "Reports: {project name}" + export buttons
 *   2. Tab bar (scrollable)
 *   3. Inline data table for active tab
 *   4. Export history below
 */

const REPORT_TABS: [string, string][] = [
  ['schedule', 'Schedule & CPM'],
  ['critical', 'Critical Path'],
  ['financial', 'Cost & Budget'],
  ['progress', 'Progress'],
  ['risk', 'Risks'],
  ['rfi', 'RFIs'],
  ['changes', 'Change Orders'],
  ['punch', 'Punch List'],
  ['safety', 'Safety'],
  ['quality', 'Quality'],
  ['procurement', 'Procurement'],
  ['labour', 'Timesheets'],
  ['documents', 'Documents'],
  ['meetings', 'Meetings'],
  ['gantt', 'Gantt'],
  ['network', 'Network'],
  ['scurve', 'S-Curve'],
]

const VISUAL_TABS = new Set(['gantt', 'network', 'scurve'])

const FORMAT_LABELS: Record<string, string> = {
  csv: 'CSV',
  xlsx: 'Excel',
  pdf: 'PDF',
  docx: 'Word',
}

const FORMAT_COLORS: Record<string, string> = {
  csv: '#22c55e',
  xlsx: '#3b82f6',
  pdf: '#ef4444',
  docx: '#6366f1',
}

// ---------------------------------------------------------------------------
// Client-side export helpers
// ---------------------------------------------------------------------------

function escapeCSV(val: string | number): string {
  const s = String(val ?? '')
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

function isNumeric(val: string | number): boolean {
  if (typeof val === 'number') return true
  const trimmed = String(val).trim()
  return trimmed !== '' && !isNaN(Number(trimmed))
}

function buildHTMLTable(title: string, headers: string[], rows: (string | number)[][], summary?: string): string {
  const headerRow = headers.map(h => `<th style="background:#1e293b;color:#f59e0b;padding:8px 12px;text-align:left;font-size:12px;border-bottom:2px solid #334155">${h}</th>`).join('')
  const dataRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#1e293b' : '#0f172a'
    const cells = row.map((v) => {
      const mono = isNumeric(v) ? 'font-family:monospace;' : ''
      return `<td style="padding:6px 12px;color:#e2e8f0;font-size:12px;border-bottom:1px solid #334155;${mono}">${v ?? ''}</td>`
    }).join('')
    return `<tr style="background:${bg}">${cells}</tr>`
  }).join('')

  const summaryHTML = summary ? `<p style="color:#94a3b8;font-size:12px;margin-bottom:12px">${summary}</p>` : ''

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
@media print{@page{size:A4 landscape;margin:10mm}}
body{font-family:Calibri,sans-serif;background:#0f172a;color:#e2e8f0;padding:20px}
h1{color:#f59e0b;border-bottom:3px solid #f59e0b;padding-bottom:6px;font-size:18px}
table{border-collapse:collapse;width:100%}
</style></head><body>
<h1>${title}</h1>
${summaryHTML}
<table><thead><tr>${headerRow}</tr></thead><tbody>${dataRows}</tbody></table>
<p style="color:#64748b;font-size:10px;margin-top:16px">Generated by BuildPro</p>
</body></html>`
}

function exportCSV(title: string, headers: string[], rows: (string | number)[][]) {
  const lines = [headers.map(escapeCSV).join(',')]
  for (const row of rows) {
    lines.push(row.map(escapeCSV).join(','))
  }
  const content = '\uFEFF' + lines.join('\r\n')
  downloadText(content, `${title.replace(/\s+/g, '_')}.csv`, 'text/csv;charset=utf-8')
}

function exportExcel(title: string, headers: string[], rows: (string | number)[][], summary?: string) {
  const html = buildHTMLTable(title, headers, rows, summary)
  triggerDownload(new Blob(['\uFEFF' + html], { type: 'application/vnd.ms-excel' }), `${title.replace(/\s+/g, '_')}.xls`)
}

function exportWord(title: string, headers: string[], rows: (string | number)[][], summary?: string) {
  const html = buildHTMLTable(title, headers, rows, summary)
  triggerDownload(new Blob(['\uFEFF' + html], { type: 'application/msword' }), `${title.replace(/\s+/g, '_')}.doc`)
}

function exportPDF(title: string, headers: string[], rows: (string | number)[][], summary?: string) {
  const html = buildHTMLTable(title, headers, rows, summary)
    + '\n<script>window.onload=function(){window.print()}<\/script>'
  triggerDownload(new Blob([html], { type: 'text/html' }), `${title.replace(/\s+/g, '_')}.html`)
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ProjectReportsPage() {
  const { projectId } = useParams()
  const pid = projectId!
  const { data: project } = useProject(projectId)
  const [activeTab, setActiveTab] = useState('schedule')
  const { showToast } = useUIStore()

  // For the "critical" tab, fetch schedule data and filter client-side
  const fetchKey = activeTab === 'critical' ? 'schedule' : activeTab
  const isVisualTab = VISUAL_TABS.has(activeTab)

  const {
    data: reportData,
    isLoading: loadingReport,
  } = useReportData(projectId, isVisualTab ? '' : fetchKey)

  // Export history (server-side exports)
  const { data: history, isLoading: loadingHistory } = useExportHistory(projectId)
  const redownload = useRedownloadExport(pid)

  // ---------------------------------------------------------------------------
  // Derive display data: for "critical" tab, filter schedule rows
  // ---------------------------------------------------------------------------
  let displayTitle = reportData?.title ?? ''
  let displayHeaders = reportData?.headers ?? []
  let displayRows = reportData?.rows ?? []
  let displaySummary = reportData?.summary

  if (activeTab === 'critical' && reportData) {
    const critIdx = reportData.headers.indexOf('Critical')
    if (critIdx >= 0) {
      displayRows = reportData.rows.filter(row => String(row[critIdx]).toLowerCase() === 'yes')
      displayTitle = displayTitle.replace('Schedule', 'Critical Path')
    }
  }

  // ---------------------------------------------------------------------------
  // Export handlers (client-side from loaded data)
  // ---------------------------------------------------------------------------
  const handleClientExport = (format: string) => {
    if (!displayHeaders.length) {
      showToast('No data to export', 'error')
      return
    }
    const safeTitle = displayTitle || activeTab
    switch (format) {
      case 'csv': exportCSV(safeTitle, displayHeaders, displayRows); break
      case 'xlsx': exportExcel(safeTitle, displayHeaders, displayRows, displaySummary); break
      case 'docx': exportWord(safeTitle, displayHeaders, displayRows, displaySummary); break
      case 'pdf': exportPDF(safeTitle, displayHeaders, displayRows, displaySummary); break
    }
    showToast(`${FORMAT_LABELS[format]} downloaded!`, 'success')
  }

  // Visual tab link targets
  const visualLinks: Record<string, { label: string; path: string }> = {
    gantt: { label: 'Gantt Chart', path: `/projects/${pid}/gantt` },
    network: { label: 'Network Diagram', path: `/projects/${pid}/network` },
    scurve: { label: 'S-Curve', path: `/projects/${pid}/scurve` },
  }

  // Export history columns
  const historyColumns = [
    { key: 'report', header: 'Report', render: (h: ExportHistoryItem) => <span className="font-medium text-bp-text">{h.report_key_display}</span> },
    { key: 'format', header: 'Format', width: '80px', render: (h: ExportHistoryItem) => <StatusBadge text={h.format_display} color={FORMAT_COLORS[h.format] || '#94a3b8'} /> },
    { key: 'rows', header: 'Rows', width: '60px', render: (h: ExportHistoryItem) => <span className="font-mono text-xs text-bp-muted">{h.row_count}</span> },
    { key: 'file', header: 'File', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{h.file_name}</span> },
    { key: 'by', header: 'Generated By', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{h.created_by_name}</span> },
    { key: 'date', header: 'Date', width: '100px', render: (h: ExportHistoryItem) => <span className="text-xs text-bp-muted">{new Date(h.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })}</span> },
    { key: 'status', header: 'Status', width: '80px', render: (h: ExportHistoryItem) => {
      const color = h.status === 'completed' ? '#22c55e' : h.status === 'failed' ? '#ef4444' : '#f59e0b'
      return <StatusBadge text={h.status_display} color={color} />
    }},
    { key: 'download', header: '', width: '90px', render: (h: ExportHistoryItem) => (
      h.status === 'completed' && h.download_available ? (
        <ActionButton variant="ghost" size="sm" onClick={() => {
          redownload.mutateAsync(h).catch(() => showToast('Download failed', 'error'))
        }}>Re-download</ActionButton>
      ) : null
    )},
  ]

  const projectName = project?.name ?? 'Project'

  return (
    <div>
      {/* 1. Header with title + export buttons */}
      <div className="flex items-center justify-between flex-wrap gap-3 mb-4">
        <h2 className="text-bp-text text-lg font-bold m-0">
          Reports: {projectName}
        </h2>
        <div className="flex gap-1.5">
          {['csv', 'xlsx', 'docx', 'pdf'].map(fmt => (
            <ActionButton
              key={fmt}
              variant="accent"
              size="sm"
              disabled={isVisualTab || loadingReport || !displayHeaders.length}
              onClick={() => handleClientExport(fmt)}
            >
              {FORMAT_LABELS[fmt]}
            </ActionButton>
          ))}
        </div>
      </div>

      {/* 2. Tab bar (scrollable) */}
      <div
        className="flex gap-1 rounded-lg p-0.5 mb-4 overflow-x-auto"
        style={{ background: '#1e293b', flexWrap: 'wrap' }}
      >
        {REPORT_TABS.map(([key, label]) => {
          const isActive = activeTab === key
          return (
            <button
              key={key}
              onClick={() => setActiveTab(key)}
              className="shrink-0 rounded-md border-none font-semibold cursor-pointer transition-colors"
              style={{
                fontSize: 12,
                padding: '6px 12px',
                background: isActive ? '#f59e0b' : 'transparent',
                color: isActive ? '#0f172a' : '#94a3b8',
              }}
            >
              {label}
            </button>
          )
        })}
      </div>

      {/* 3. Active tab content */}
      {isVisualTab ? (
        <SectionCard>
          <div className="flex flex-col items-center gap-4 py-8">
            <div className="text-bp-muted text-sm">
              This report is best viewed on its dedicated page.
            </div>
            <Link to={visualLinks[activeTab].path}>
              <ActionButton variant="accent" size="md">
                View {visualLinks[activeTab].label}
              </ActionButton>
            </Link>
          </div>
        </SectionCard>
      ) : loadingReport ? (
        <LoadingState rows={6} />
      ) : displayRows.length === 0 ? (
        <EmptyState
          icon="&#128202;"
          title="No data"
          description={`No ${REPORT_TABS.find(t => t[0] === activeTab)?.[1] ?? activeTab} data found for this project.`}
        />
      ) : (
        <SectionCard>
          {displaySummary && (
            <p className="text-bp-muted text-xs mb-3">{displaySummary}</p>
          )}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-xs">
              <thead>
                <tr>
                  {displayHeaders.map((h, i) => (
                    <th
                      key={i}
                      className="text-left font-semibold px-3 py-2 whitespace-nowrap"
                      style={{
                        background: '#1e293b',
                        color: '#f59e0b',
                        borderBottom: '2px solid #334155',
                        fontSize: 12,
                      }}
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {displayRows.map((row, ri) => (
                  <tr
                    key={ri}
                    style={{ background: ri % 2 === 0 ? '#1e293b' : '#0f172a' }}
                  >
                    {row.map((cell, ci) => (
                      <td
                        key={ci}
                        className={`px-3 py-1.5 text-bp-text whitespace-nowrap ${isNumeric(cell) ? 'font-mono' : ''}`}
                        style={{
                          borderBottom: '1px solid #334155',
                          fontSize: 12,
                        }}
                      >
                        {cell ?? ''}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="text-bp-muted text-[11px] mt-2">
            {displayRows.length} row{displayRows.length !== 1 ? 's' : ''}
          </div>
        </SectionCard>
      )}

      {/* 4. Export History */}
      <div className="mt-6">
        <div className="mb-2 text-sm font-semibold text-bp-text">Export History</div>
        {loadingHistory ? <LoadingState rows={3} /> :
          (history && history.length > 0) ? (
            <DataTable columns={historyColumns} data={history} emptyText="No exports yet" />
          ) : (
            <EmptyState icon="&#128202;" title="No exports yet" description="Generate a report to see it here." />
          )
        }
      </div>
    </div>
  )
}
