# Generated by Django 5.2.12 on 2026-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='equipment',
            field=models.TextField(blank=True, default='', help_text='Equipment on site'),
        ),
    ]
