# Generated by Django 5.2.12 on 2026-03-14 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code e.g. A, B1, C2a', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('phase', models.CharField(blank=True, default='', help_text='Phase/group label', max_length=100)),
                ('duration_days', models.IntegerField(default=0)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('early_start', models.IntegerField(default=0, help_text='Day offset from project start')),
                ('early_finish', models.IntegerField(default=0)),
                ('late_start', models.IntegerField(default=0)),
                ('late_finish', models.IntegerField(default=0)),
                ('total_float', models.IntegerField(default=0, help_text='Slack / total float')),
                ('is_critical', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0, help_text='0-100 percent complete')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('resource', models.CharField(blank=True, default='', help_text='Assigned resource/team', max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_parent', models.BooleanField(default=False, help_text='True for summary/phase tasks')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scheduling.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_task',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('achieved', 'Achieved'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='scheduling.projecttask')),
            ],
            options={
                'db_table': 'scheduling_milestone',
                'ordering': ['sort_order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='projects.project')),
            ],
            options={
                'db_table': 'scheduling_baseline',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BaselineTaskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField(default=0)),
                ('early_start', models.IntegerField(default=0)),
                ('early_finish', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_snapshots', to='scheduling.projecttask')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scheduling.schedulebaseline')),
            ],
            options={
                'db_table': 'scheduling_baseline_snapshot',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='scheduling.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='scheduling.projecttask')),
            ],
            options={
                'db_table': 'scheduling_dependency',
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
